osx_image: xcode8.3
language: objective-c
podfile: Example/Podfile
script:
- set -o pipefail && xcodebuild test -workspace Example/DDSpiderChart.xcworkspace -scheme DDSpiderChart-Example -sdk iphonesimulator10.3 -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.3' ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
